import { NextRequest, NextResponse } from 'next/server';
import { getSessionUser, enforceDocumentOwnership } from '@/lib/security/auth';
import { 
  getDocument, 
  getAnalysisResult, 
  getAttentionAreas, 
  getObligations, 
  getChecklistItems 
} from '@/lib/db';

export async function POST(req: NextRequest) {
  try {
    const user = await getSessionUser(req);
    const body = await req.json();
    const { documentId, format = 'txt' } = body;

    if (!documentId) {
      return NextResponse.json({ success: false, error: 'documentId is required.' }, { status: 400 });
    }

    const doc = getDocument(documentId);
    if (!doc || !enforceDocumentOwnership(doc.userId, user.id)) {
      return NextResponse.json({ success: false, error: 'Document not found or access denied.' }, { status: 404 });
    }

    const analysis = getAnalysisResult(documentId);
    const attentionAreas = getAttentionAreas(documentId);
    const obligations = getObligations(documentId);
    const checklist = getChecklistItems(documentId);

    const timestamp = new Date().toUTCString();
    const disclaimer = 
      'DISCLAIMER: This report is generated by LexiLens for informational and preparation purposes only.\n' +
      'It does not constitute legal advice, an attorney-client relationship, or a formal legal opinion.\n' +
      'Consult a licensed attorney for binding legal counsel.';

    if (format === 'markdown' || format === 'md') {
      let md = `# LexiLens Analysis Report: ${doc.title}\n\n`;
      md += `*Generated: ${timestamp}*\n\n`;
      md += `> **Important Disclaimer**\n> ${disclaimer}\n\n---\n\n`;

      md += `## 1. Executive Summary\n${analysis?.summary || 'N/A'}\n\n`;

      md += `## 2. Document Overview\n`;
      md += `- **Governing Law:** ${analysis?.overview.governingLaw}\n`;
      md += `- **Effective Date:** ${analysis?.overview.effectiveDate}\n`;
      md += `- **Renewal Terms:** ${analysis?.overview.renewalInfo}\n`;
      md += `- **Termination Terms:** ${analysis?.overview.terminationInfo}\n\n`;

      md += `## 3. Attention Areas & Considerations\n`;
      for (const a of attentionAreas) {
        md += `### [${a.severity.toUpperCase()}] ${a.title} (Page ${a.sourcePage})\n`;
        md += `- **What the document says:** ${a.whatItSays}\n`;
        md += `- **Why it matters:** ${a.whyItMatters}\n`;
        md += `- **Question to consider:** *"${a.questionToConsider}"*\n\n`;
      }

      md += `## 4. Key Obligations\n`;
      for (const o of obligations) {
        md += `- [${o.isCompleted ? 'X' : ' '}] **${o.party}:** ${o.obligation} | *Deadline: ${o.deadline}* (Page ${o.sourcePage})\n`;
      }
      md += `\n`;

      md += `## 5. Action Checklist\n`;
      for (const c of checklist) {
        md += `- [${c.isCompleted ? 'X' : ' '}] (${c.category}) ${c.task}\n`;
      }

      return new NextResponse(md, {
        headers: {
          'Content-Type': 'text/markdown; charset=utf-8',
          'Content-Disposition': `attachment; filename="${doc.fileName}-analysis.md"`
        }
      });
    }

    // Default Plain Text Export
    let txt = `================================================================================\n`;
    txt += `LEXILENS LEGAL DOCUMENT ANALYSIS REPORT\n`;
    txt += `Document: ${doc.title}\n`;
    txt += `Generated: ${timestamp}\n`;
    txt += `================================================================================\n\n`;
    txt += `${disclaimer}\n\n`;
    txt += `--------------------------------------------------------------------------------\n`;
    txt += `1. EXECUTIVE SUMMARY\n`;
    txt += `--------------------------------------------------------------------------------\n`;
    txt += `${analysis?.summary || 'N/A'}\n\n`;

    txt += `--------------------------------------------------------------------------------\n`;
    txt += `2. DOCUMENT OVERVIEW & METADATA\n`;
    txt += `--------------------------------------------------------------------------------\n`;
    txt += `Governing Law:    ${analysis?.overview.governingLaw}\n`;
    txt += `Effective Date:   ${analysis?.overview.effectiveDate}\n`;
    txt += `Renewal Info:     ${analysis?.overview.renewalInfo}\n`;
    txt += `Termination Info: ${analysis?.overview.terminationInfo}\n\n`;

    txt += `--------------------------------------------------------------------------------\n`;
    txt += `3. ATTENTION AREAS & RISKS\n`;
    txt += `--------------------------------------------------------------------------------\n`;
    for (const a of attentionAreas) {
      txt += `[${a.severity.toUpperCase()}] ${a.title} (Page ${a.sourcePage})\n`;
      txt += `  What it says:        ${a.whatItSays}\n`;
      txt += `  Why it matters:      ${a.whyItMatters}\n`;
      txt += `  Question to discuss: ${a.questionToConsider}\n\n`;
    }

    txt += `--------------------------------------------------------------------------------\n`;
    txt += `4. OBLIGATION TRACKER\n`;
    txt += `--------------------------------------------------------------------------------\n`;
    for (const o of obligations) {
      txt += `[${o.isCompleted ? 'COMPLETED' : 'PENDING'}] ${o.party}: ${o.obligation}\n`;
      txt += `  Deadline: ${o.deadline} | Page ${o.sourcePage}\n\n`;
    }

    txt += `--------------------------------------------------------------------------------\n`;
    txt += `5. LAWYER CONSULTATION CHECKLIST\n`;
    txt += `--------------------------------------------------------------------------------\n`;
    for (const c of checklist) {
      txt += `[${c.isCompleted ? 'X' : ' '}] (${c.category}) ${c.task}\n`;
    }

    return new NextResponse(txt, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${doc.fileName}-analysis.txt"`
      }
    });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
